CREATE TABLE person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) UNIQUE NOT NULL,
    year int CHECK(year > 1900) NOT NULL
);

CREATE TABLE book(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    author varchar(50) NOT NULL,
    year int CHECK(year > 0) NOT NULL,
    person_id int REFERENCES person(id) ON DELETE SET NULL
);